### ISSUE TITLE
Mixpanel does not accept campaign / utm parameters

### ISSUE THREAD

**Issue by lambtron** [segment-integrations/integration-mixpanel#6]
Mixpanel's http api does not have a way to accept campaign / utm parameters.
https://mixpanel.com/help/reference/http

Some customers are interested in this stuff. Should we have an option for passing utm stuff to Mixpanel and just pass them under `traits`?

From customer: "But maybe a simple way would be to map campaign.source to campaignSource, campaign.term to campaignTerm... And have them as "normal" properties."

Thoughts? @amillet89 @ndhoule

**Comment by f2prateek** [comment]
We can see how they send it on Android/iOS and just do that here (even though it's undocumented).

**Comment by pauloschilling** [comment]
Since I'm watching the GitHub of each integration we're using, I received a
notification for this issue, but let me ask you something, are you aware
that Mixpanel automatically tracks utm_* params when using their JS
library? And I do believe Segment's Analytics.js automatically loads their
library.

Here:
https://mixpanel.com/help/questions/articles/can-i-track-google-analytics-style-utm-tags-with-mixpanel

I was thinking, at least for an application using cached pages, the best
practice is to always ignore the query string, so doesn't makes sense
tracking this server-side, only client-side, and this is already working
with the Mixpanel JS lib. Anyway, I think if you just send a page view to
Mixpanel, from the server, including the query string, they will handle it
automatically as well. After it, every event will be linked to that
specific page view, allowing the customer to figure out the original
campaign for the event or conversion.

Hope you don't mind if I try to contribute with you guys, we're really big
fans, not just customers. :)

**Comment by f2prateek** [comment]
Not at all, we appreciate your input!

As you said, the Mixpanel JS library and bundled Mixpanel mobile SDK would work client side for collecting UTM parameters. However adding it to the server side integrations means that any platform can send that data so that it shows up correctly in Mixpanel, which is pretty awesome for things like replay.

**Comment by hankim813** [comment]
This has been implemented here: https://github.com/segment-integrations/integration-mixpanel/blob/master/lib/index.js#L470-L477
